### ISSUE TITLE
Specify RAxML binary

### ISSUE THREAD

**Issue by trvrb** [nextstrain/janus#7]
Originally from point 4 here: https://github.com/nextstrain/janus/pull/1#issuecomment-323542211

Currently RAxML is set to `RAxML-HPC` here:

https://github.com/nextstrain/janus/blob/master/install.sh#L20

This should be configurable somehow as specific binary makes a huge difference in RAxML run speed. Different hardware requires different binaries however.

**Comment by huddlej** [comment]
Since conda installs binaries for all RAxML builds, I did some benchmarking of RAxML versions on the rhino cluster. Each version of RAxML was run for 10 different iterations and benchmarked using Snakemake’s built-in benchmarking utility. The input alignment contained 684 sequences, representing a non-trivial data set for RAxML. I confirmed that the rhino nodes I used have AVX2 and SSE3 instructions available.

One caveat to this analysis is that the non-PTHREADS versions of RAxML don’t support multithreading and the PTHREADS versions don’t allow threads to be less than 2. So, all non-PTHREADS versions were run with 1 thread and all PTHREADS versions were run with 2 threads.

Below is the distribution of run times per version with one data point per iteration.  

![image](https://user-images.githubusercontent.com/85372/30084378-fc38ddbc-9246-11e7-8bdd-f372fb826ab5.png)

If we take into account the fact that all of the PTHREADS versions ran with 2 threads and the other versions all ran with 1 thread by using thread seconds (number of seconds * threads), we get the following distributions.

![image](https://user-images.githubusercontent.com/85372/30084388-0dcb1fb8-9247-11e7-9025-a55fa88f3971.png)

The best performance obviously comes from using more threads, so picking one of the PTHREADS versions with at least two threads would be an improvement over the HPC single-threaded version. Both vanilla PTHREADS and PTHREADS-AVX2 perform similarly well with a more consistent performance from the AVX2 build. This might be the best version to use on the rhino cluster.

If this seems like a fair analysis and conclusion, I can make the switch janus's RAxML version.
