### ISSUE TITLE
Reassess use of wildcards in snakemake

### ISSUE THREAD

**Issue by trvrb** [nextstrain/janus#9]
Originally point 7 here: https://github.com/nextstrain/janus/pull/1#issuecomment-323542211

The use of wildcards like `wildcards: virus=zika, lineage=all, segment=all, resolution=all` is not very future proof. We can have different build hierarchies for different viruses. Many viruses lack `lineages` other might have `geo`. Also this cases resulting auspice JSONs to look like: `zika_all_all_all_meta.json`. This doesn't match what auspice actually wants and so it's necessary to convert `zika_all_all_all_meta.json` to `zika_meta.json` on S3 push here: https://github.com/nextstrain/janus/blob/master/Snakefile#L310.

This needs to get figured out. This should be done in conversation with @jameshadfield as he's thinking about how to do an auspice `datasets.json` config. This might be a different file from janus's `config.json` but they both should reflect the same _intent_.

**Comment by huddlej** [comment]
The use of the "all" placeholders in the original implementation of the Snakemake builds was a workaround for the fact that Snakemake rules need explicitly defined output file names to build a dependency graph. An alternate approach to the "all" placeholders would be to reorganize the configuration file format and assign specific names to each build. Then Snakemake could use these build names as prefixes for the actual outputs it creates (e.g., a build named "zika" would create an auspice output like "zika_meta.json").

An alternative config format I've been considering would look something like this.

```json
{
    "builds": {
        "zika": {
            "virus": "zika",
            "viruses_per_month": 15,
            "resolve_method": "choose_genbank"
        } 
    }
}
```

Then the complete set of builds for H3N2, dengue, H7N9, Zika, and Ebola would look like this with an additional "defaults" section for values that are shared across all builds for a given virus.

```json
{
    "builds": {
        "flu_h3n2_ha_2y": {
            "virus": "flu",
            "lineage": "h3n2",
            "resolution": "2y",
            "segments": ["ha"],
            "viruses_per_month": 90
        },
        "flu_h3n2_ha_3y": {
            "virus": "flu",
            "lineage": "h3n2",
            "resolution": "3y",
            "segments": ["ha"],
            "viruses_per_month": 60
        },
        "flu_h3n2_ha_6y": {
            "virus": "flu",
            "lineage": "h3n2",
            "resolution": "6y",
            "segments": ["ha"],
            "viruses_per_month": 24
        },
        "flu_h3n2_ha_12y": {
            "virus": "flu",
            "lineage": "h3n2",
            "resolution": "12y",
            "segments": ["ha"],
            "viruses_per_month": 12
        },
        "zika": {
            "virus": "zika",
            "viruses_per_month": 15,
            "resolve_method": "choose_genbank"
        },
        "ebola": {
            "virus": "ebola",
            "viruses_per_month": 100,
            "resolve_method": "choose_genbank"
        },
        "dengue_denv1": {
            "virus": "dengue",
            "lineage": "denv1"
        },
        "dengue_denv2": {
            "virus": "dengue",
            "lineage": "denv2"
        },
        "dengue_denv3": {
            "virus": "dengue",
            "lineage": "denv3"
        },
        "dengue_denv4": {
            "virus": "dengue",
            "lineage": "denv4"
        },
        "avian": {
            "virus": "avian",
            "lineage": "h7n9",
            "segments": [
                "pb2",
                "pb1",
                "pa",
                "ha",
                "np",
                "na",
                "mp",
                "ns"
            ],
            "viruses_per_month": 0
        }
    },
    "defaults": {
        "flu": {
            "has_titers": true,
            "sampling": "even"
        },
        "dengue": {
            "has_titers": true,
            "process_arguments": "--no_tree_freqs --no_mut_freqs --no_titers",
            "viruses_per_month": 3
        }
    }
}
```

This implementation is more verbose than the current hierarchical approach, but the flat structure allows us to be more flexible in how we define individual builds and the repetition might be a small price to pay for that flexibility and readability. It would also allow us to request builds with syntax like this:

```bash
# Run all flu builds.
./janus --config builds="virus:flu"

# Run all ebola and zika builds.
./janus --config builds="virus:zika,virus:ebola"

# Run a specific flu build.
./janus --config builds="flu_h3n2_ha_3y"

# Run all builds for the H3N2 lineage.
./janus --config builds="lineage:h3n2"
```

Or if build names follow a consistent naming pattern, we could just use wildcards like so:

```bash
# Run all flu builds.
./janus --config builds="flu_*"

# Run all builds for the H3N2 lineage.
./janus --config builds="flu_h3n2_*"
```

Another similar format would implement the builds as a list of dictionaries instead of a dictionary of dictionaries. Each build dictionary would contain an explicit "name" or "id" field that would provide the same functionality as the dictionary key does in the examples above. This list of dictionaries approach would make the list of builds similar to a list of JSON records from a database. One could imagine getting fancier in the distant future and storing all of these configurations in a RethinkDB or MongoDB table.
